#!/usr/bin/env python3

"""
ECE Project Mic-1
Title: Program Converter for mic1 files
Author: Florian Zwittnigg
Date: 17.11.2021
Rev.: 1.0 
"""

import sys
import argparse

# Reading the file and hand over the content to main
def read_file(filename:str):
        f = open(f'{filename}.mic1', mode='rb')
        fileContent = f.read()
        f.close()

        return fileContent

# convert binary data to hex dataformat for ASCII
def convert_content(fileContent:bytes):
        hex_string = fileContent.hex()
        
        n = 9
        split_strings = [hex_string[index : index + n] + "\n" for index in range(0, len(hex_string), n)]

        return split_strings

# create .txt-File in same directory and write the converted data into it
def write_file(fileContent, filename):
        file = open(f'{filename}.txt', "w")

        file.writelines(fileContent)
        
        file.close()

if __name__=='__main__':
    #parsing commandline
    parser = argparse.ArgumentParser(description='Convert Binary to ASCII')
    parser.add_argument('filename', help='filename of binaryfile without file extension')
    args = parser.parse_args()
    
    content_of_file = read_file(args.filename)
    writable_content = convert_content(content_of_file)      
    write_file(writable_content, args.filename)